// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteAccountCashByIdData,
  DeleteAccountCashByIdErrors,
  DeleteAccountCashByIdResponses,
  DeleteAccountPropertiesByIdData,
  DeleteAccountPropertiesByIdErrors,
  DeleteAccountPropertiesByIdResponses,
  DeleteAccountsByIdData,
  DeleteAccountsByIdErrors,
  DeleteAccountsByIdResponses,
  DeleteEventCashFlowsByIdData,
  DeleteEventCashFlowsByIdErrors,
  DeleteEventCashFlowsByIdResponses,
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
  DeleteIssuersByIdData,
  DeleteIssuersByIdErrors,
  DeleteIssuersByIdResponses,
  DeleteSecuritiesByIdData,
  DeleteSecuritiesByIdErrors,
  DeleteSecuritiesByIdResponses,
  DeleteSecurityDescriptionsByIdData,
  DeleteSecurityDescriptionsByIdErrors,
  DeleteSecurityDescriptionsByIdResponses,
  DeleteSecurityEventCashFlowsByIdData,
  DeleteSecurityEventCashFlowsByIdErrors,
  DeleteSecurityEventCashFlowsByIdResponses,
  DeleteSecurityQuotesByIdData,
  DeleteSecurityQuotesByIdErrors,
  DeleteSecurityQuotesByIdResponses,
  DeleteTransactionCashFlowsByIdData,
  DeleteTransactionCashFlowsByIdErrors,
  DeleteTransactionCashFlowsByIdResponses,
  DeleteTransactionsByIdData,
  DeleteTransactionsByIdErrors,
  DeleteTransactionsByIdResponses,
  GetAccountCashByIdData,
  GetAccountCashByIdErrors,
  GetAccountCashByIdResponses,
  GetAccountCashData,
  GetAccountCashErrors,
  GetAccountCashResponses,
  GetAccountPropertiesByIdData,
  GetAccountPropertiesByIdErrors,
  GetAccountPropertiesByIdResponses,
  GetAccountPropertiesData,
  GetAccountPropertiesErrors,
  GetAccountPropertiesResponses,
  GetAccountsAllStatsData,
  GetAccountsAllStatsErrors,
  GetAccountsAllStatsResponses,
  GetAccountsByIdData,
  GetAccountsByIdErrors,
  GetAccountsByIdResponses,
  GetAccountsData,
  GetAccountsErrors,
  GetAccountsResponses,
  GetActuatorConfigpropsByPrefixData,
  GetActuatorConfigpropsByPrefixErrors,
  GetActuatorConfigpropsByPrefixResponses,
  GetActuatorConfigpropsData,
  GetActuatorConfigpropsResponses,
  GetActuatorData,
  GetActuatorHealthData,
  GetActuatorHealthResponses,
  GetActuatorInfoData,
  GetActuatorInfoResponses,
  GetActuatorResponses,
  GetCashFlowTypesByIdData,
  GetCashFlowTypesByIdErrors,
  GetCashFlowTypesByIdResponses,
  GetCashFlowTypesData,
  GetCashFlowTypesErrors,
  GetCashFlowTypesResponses,
  GetEventCashFlowsByIdData,
  GetEventCashFlowsByIdErrors,
  GetEventCashFlowsByIdResponses,
  GetEventCashFlowsData,
  GetEventCashFlowsErrors,
  GetEventCashFlowsResponses,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairData,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairErrors,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses,
  GetForeignExchangeRatesData,
  GetForeignExchangeRatesErrors,
  GetForeignExchangeRatesResponses,
  GetIssuersByIdData,
  GetIssuersByIdErrors,
  GetIssuersByIdResponses,
  GetIssuersData,
  GetIssuersErrors,
  GetIssuersResponses,
  GetPortfolioOpenFormatRecordsData,
  GetPortfolioOpenFormatRecordsErrors,
  GetPortfolioOpenFormatRecordsResponses,
  GetSecuritiesByIdData,
  GetSecuritiesByIdErrors,
  GetSecuritiesByIdResponses,
  GetSecuritiesData,
  GetSecuritiesErrors,
  GetSecuritiesResponses,
  GetSecurityDescriptionsByIdData,
  GetSecurityDescriptionsByIdErrors,
  GetSecurityDescriptionsByIdResponses,
  GetSecurityDescriptionsData,
  GetSecurityDescriptionsErrors,
  GetSecurityDescriptionsResponses,
  GetSecurityEventCashFlowsByIdData,
  GetSecurityEventCashFlowsByIdErrors,
  GetSecurityEventCashFlowsByIdResponses,
  GetSecurityEventCashFlowsData,
  GetSecurityEventCashFlowsErrors,
  GetSecurityEventCashFlowsResponses,
  GetSecurityQuotesByIdData,
  GetSecurityQuotesByIdErrors,
  GetSecurityQuotesByIdResponses,
  GetSecurityQuotesData,
  GetSecurityQuotesErrors,
  GetSecurityQuotesResponses,
  GetTransactionCashFlowsByIdData,
  GetTransactionCashFlowsByIdErrors,
  GetTransactionCashFlowsByIdResponses,
  GetTransactionCashFlowsData,
  GetTransactionCashFlowsErrors,
  GetTransactionCashFlowsResponses,
  GetTransactionsByIdData,
  GetTransactionsByIdErrors,
  GetTransactionsByIdResponses,
  GetTransactionsData,
  GetTransactionsErrors,
  GetTransactionsResponses,
  PostAccountCashData,
  PostAccountCashErrors,
  PostAccountCashResponses,
  PostAccountPropertiesData,
  PostAccountPropertiesErrors,
  PostAccountPropertiesResponses,
  PostAccountsData,
  PostAccountsErrors,
  PostAccountsResponses,
  PostAppShutdownData,
  PostAppShutdownErrors,
  PostAppShutdownResponses,
  PostEventCashFlowsData,
  PostEventCashFlowsErrors,
  PostEventCashFlowsResponses,
  PostForeignExchangeRatesData,
  PostForeignExchangeRatesErrors,
  PostForeignExchangeRatesResponses,
  PostIssuersData,
  PostIssuersErrors,
  PostIssuersResponses,
  PostPortfolioOpenFormatRecordsData,
  PostPortfolioOpenFormatRecordsErrors,
  PostPortfolioOpenFormatRecordsResponses,
  PostSecuritiesData,
  PostSecuritiesErrors,
  PostSecuritiesResponses,
  PostSecurityDescriptionsData,
  PostSecurityDescriptionsErrors,
  PostSecurityDescriptionsResponses,
  PostSecurityEventCashFlowsData,
  PostSecurityEventCashFlowsErrors,
  PostSecurityEventCashFlowsResponses,
  PostSecurityQuotesData,
  PostSecurityQuotesErrors,
  PostSecurityQuotesResponses,
  PostTransactionCashFlowsData,
  PostTransactionCashFlowsErrors,
  PostTransactionCashFlowsResponses,
  PostTransactionsData,
  PostTransactionsErrors,
  PostTransactionsResponses,
  PutAccountCashByIdData,
  PutAccountCashByIdErrors,
  PutAccountCashByIdResponses,
  PutAccountPropertiesByIdData,
  PutAccountPropertiesByIdErrors,
  PutAccountPropertiesByIdResponses,
  PutAccountsByIdData,
  PutAccountsByIdErrors,
  PutAccountsByIdResponses,
  PutEventCashFlowsByIdData,
  PutEventCashFlowsByIdErrors,
  PutEventCashFlowsByIdResponses,
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
  PutIssuersByIdData,
  PutIssuersByIdErrors,
  PutIssuersByIdResponses,
  PutSecuritiesByIdData,
  PutSecuritiesByIdErrors,
  PutSecuritiesByIdResponses,
  PutSecurityDescriptionsByIdData,
  PutSecurityDescriptionsByIdErrors,
  PutSecurityDescriptionsByIdResponses,
  PutSecurityEventCashFlowsByIdData,
  PutSecurityEventCashFlowsByIdErrors,
  PutSecurityEventCashFlowsByIdResponses,
  PutSecurityQuotesByIdData,
  PutSecurityQuotesByIdErrors,
  PutSecurityQuotesByIdResponses,
  PutTransactionCashFlowsByIdData,
  PutTransactionCashFlowsByIdErrors,
  PutTransactionCashFlowsByIdResponses,
  PutTransactionsByIdData,
  PutTransactionsByIdErrors,
  PutTransactionsByIdResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get statistics for all accounts
 */
export const getAccountsAllStats = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountsAllStatsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAccountsAllStatsResponses,
    GetAccountsAllStatsErrors,
    ThrowOnError
  >({ url: '/accounts/all/stats', ...options });

/**
 * Actuator root web endpoint
 */
export const getActuator = <ThrowOnError extends boolean = false>(
  options?: Options<GetActuatorData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetActuatorResponses, unknown, ThrowOnError>({
    url: '/actuator',
    ...options,
  });

/**
 * Actuator web endpoint 'configprops'
 */
export const getActuatorConfigprops = <ThrowOnError extends boolean = false>(
  options?: Options<GetActuatorConfigpropsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetActuatorConfigpropsResponses,
    unknown,
    ThrowOnError
  >({ url: '/actuator/configprops', ...options });

/**
 * Actuator web endpoint 'configprops-prefix'
 */
export const getActuatorConfigpropsByPrefix = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetActuatorConfigpropsByPrefixData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetActuatorConfigpropsByPrefixResponses,
    GetActuatorConfigpropsByPrefixErrors,
    ThrowOnError
  >({ url: '/actuator/configprops/{prefix}', ...options });

/**
 * Actuator web endpoint 'health'
 */
export const getActuatorHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetActuatorHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetActuatorHealthResponses,
    unknown,
    ThrowOnError
  >({ url: '/actuator/health', ...options });

/**
 * Actuator web endpoint 'info'
 */
export const getActuatorInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetActuatorInfoData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetActuatorInfoResponses,
    unknown,
    ThrowOnError
  >({ url: '/actuator/info', ...options });

export const getAccountCash = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountCashData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAccountCashResponses,
    GetAccountCashErrors,
    ThrowOnError
  >({ url: '/api/v1/account-cash', ...options });

export const postAccountCash = <ThrowOnError extends boolean = false>(
  options: Options<PostAccountCashData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostAccountCashResponses,
    PostAccountCashErrors,
    ThrowOnError
  >({
    url: '/api/v1/account-cash',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteAccountCashById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAccountCashByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAccountCashByIdResponses,
    DeleteAccountCashByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/account-cash/{id}', ...options });

export const getAccountCashById = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountCashByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAccountCashByIdResponses,
    GetAccountCashByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/account-cash/{id}', ...options });

export const putAccountCashById = <ThrowOnError extends boolean = false>(
  options: Options<PutAccountCashByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutAccountCashByIdResponses,
    PutAccountCashByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/account-cash/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getAccountProperties = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountPropertiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAccountPropertiesResponses,
    GetAccountPropertiesErrors,
    ThrowOnError
  >({ url: '/api/v1/account-properties', ...options });

export const postAccountProperties = <ThrowOnError extends boolean = false>(
  options: Options<PostAccountPropertiesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostAccountPropertiesResponses,
    PostAccountPropertiesErrors,
    ThrowOnError
  >({
    url: '/api/v1/account-properties',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteAccountPropertiesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAccountPropertiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAccountPropertiesByIdResponses,
    DeleteAccountPropertiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/account-properties/{id}', ...options });

export const getAccountPropertiesById = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountPropertiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAccountPropertiesByIdResponses,
    GetAccountPropertiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/account-properties/{id}', ...options });

export const putAccountPropertiesById = <ThrowOnError extends boolean = false>(
  options: Options<PutAccountPropertiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutAccountPropertiesByIdResponses,
    PutAccountPropertiesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/account-properties/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAccountsResponses,
    GetAccountsErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts', ...options });

export const postAccounts = <ThrowOnError extends boolean = false>(
  options: Options<PostAccountsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostAccountsResponses,
    PostAccountsErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deletes the account and all associated data, including all transactions
 */
export const deleteAccountsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAccountsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAccountsByIdResponses,
    DeleteAccountsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{id}', ...options });

export const getAccountsById = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAccountsByIdResponses,
    GetAccountsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/accounts/{id}', ...options });

export const putAccountsById = <ThrowOnError extends boolean = false>(
  options: Options<PutAccountsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutAccountsByIdResponses,
    PutAccountsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/accounts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getCashFlowTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetCashFlowTypesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCashFlowTypesResponses,
    GetCashFlowTypesErrors,
    ThrowOnError
  >({ url: '/api/v1/cash-flow-types', ...options });

export const getCashFlowTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetCashFlowTypesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCashFlowTypesByIdResponses,
    GetCashFlowTypesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/cash-flow-types/{id}', ...options });

export const getEventCashFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetEventCashFlowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetEventCashFlowsResponses,
    GetEventCashFlowsErrors,
    ThrowOnError
  >({ url: '/api/v1/event-cash-flows', ...options });

export const postEventCashFlows = <ThrowOnError extends boolean = false>(
  options: Options<PostEventCashFlowsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostEventCashFlowsResponses,
    PostEventCashFlowsErrors,
    ThrowOnError
  >({
    url: '/api/v1/event-cash-flows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteEventCashFlowsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteEventCashFlowsByIdResponses,
    DeleteEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/event-cash-flows/{id}', ...options });

export const getEventCashFlowsById = <ThrowOnError extends boolean = false>(
  options: Options<GetEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEventCashFlowsByIdResponses,
    GetEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/event-cash-flows/{id}', ...options });

export const putEventCashFlowsById = <ThrowOnError extends boolean = false>(
  options: Options<PutEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutEventCashFlowsByIdResponses,
    PutEventCashFlowsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/event-cash-flows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getForeignExchangeRates = <ThrowOnError extends boolean = false>(
  options?: Options<GetForeignExchangeRatesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetForeignExchangeRatesResponses,
    GetForeignExchangeRatesErrors,
    ThrowOnError
  >({ url: '/api/v1/foreign-exchange-rates', ...options });

export const postForeignExchangeRates = <ThrowOnError extends boolean = false>(
  options: Options<PostForeignExchangeRatesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostForeignExchangeRatesResponses,
    PostForeignExchangeRatesErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getForeignExchangeRatesCurrencyPairsByCurrencyPair = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses,
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}',
    ...options,
  });

export const deleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDate =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
      ThrowOnError
    >,
  ) =>
    (options.client ?? client).delete<
      DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
      DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
      ThrowOnError
    >({
      url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}/dates/{date}',
      ...options,
    });

export const getForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}/dates/{date}',
    ...options,
  });

export const putForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
    PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}/dates/{date}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getIssuers = <ThrowOnError extends boolean = false>(
  options?: Options<GetIssuersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetIssuersResponses,
    GetIssuersErrors,
    ThrowOnError
  >({ url: '/api/v1/issuers', ...options });

export const postIssuers = <ThrowOnError extends boolean = false>(
  options: Options<PostIssuersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostIssuersResponses,
    PostIssuersErrors,
    ThrowOnError
  >({
    url: '/api/v1/issuers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteIssuersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIssuersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteIssuersByIdResponses,
    DeleteIssuersByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/issuers/{id}', ...options });

export const getIssuersById = <ThrowOnError extends boolean = false>(
  options: Options<GetIssuersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetIssuersByIdResponses,
    GetIssuersByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/issuers/{id}', ...options });

export const putIssuersById = <ThrowOnError extends boolean = false>(
  options: Options<PutIssuersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutIssuersByIdResponses,
    PutIssuersByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/issuers/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getSecurities = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecuritiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecuritiesResponses,
    GetSecuritiesErrors,
    ThrowOnError
  >({ url: '/api/v1/securities', ...options });

export const postSecurities = <ThrowOnError extends boolean = false>(
  options: Options<PostSecuritiesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecuritiesResponses,
    PostSecuritiesErrors,
    ThrowOnError
  >({
    url: '/api/v1/securities',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deletes all security-related transactions across all accounts
 */
export const deleteSecuritiesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecuritiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecuritiesByIdResponses,
    DeleteSecuritiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/securities/{id}', ...options });

export const getSecuritiesById = <ThrowOnError extends boolean = false>(
  options: Options<GetSecuritiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecuritiesByIdResponses,
    GetSecuritiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/securities/{id}', ...options });

export const putSecuritiesById = <ThrowOnError extends boolean = false>(
  options: Options<PutSecuritiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecuritiesByIdResponses,
    PutSecuritiesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/securities/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getSecurityDescriptions = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecurityDescriptionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecurityDescriptionsResponses,
    GetSecurityDescriptionsErrors,
    ThrowOnError
  >({ url: '/api/v1/security-descriptions', ...options });

export const postSecurityDescriptions = <ThrowOnError extends boolean = false>(
  options: Options<PostSecurityDescriptionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecurityDescriptionsResponses,
    PostSecurityDescriptionsErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-descriptions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteSecurityDescriptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSecurityDescriptionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecurityDescriptionsByIdResponses,
    DeleteSecurityDescriptionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-descriptions/{id}', ...options });

export const getSecurityDescriptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSecurityDescriptionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecurityDescriptionsByIdResponses,
    GetSecurityDescriptionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-descriptions/{id}', ...options });

export const putSecurityDescriptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSecurityDescriptionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecurityDescriptionsByIdResponses,
    PutSecurityDescriptionsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-descriptions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getSecurityEventCashFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecurityEventCashFlowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecurityEventCashFlowsResponses,
    GetSecurityEventCashFlowsErrors,
    ThrowOnError
  >({ url: '/api/v1/security-event-cash-flows', ...options });

export const postSecurityEventCashFlows = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostSecurityEventCashFlowsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecurityEventCashFlowsResponses,
    PostSecurityEventCashFlowsErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-event-cash-flows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteSecurityEventCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSecurityEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecurityEventCashFlowsByIdResponses,
    DeleteSecurityEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-event-cash-flows/{id}', ...options });

export const getSecurityEventCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSecurityEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecurityEventCashFlowsByIdResponses,
    GetSecurityEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-event-cash-flows/{id}', ...options });

export const putSecurityEventCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSecurityEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecurityEventCashFlowsByIdResponses,
    PutSecurityEventCashFlowsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-event-cash-flows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getSecurityQuotes = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecurityQuotesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecurityQuotesResponses,
    GetSecurityQuotesErrors,
    ThrowOnError
  >({ url: '/api/v1/security-quotes', ...options });

export const postSecurityQuotes = <ThrowOnError extends boolean = false>(
  options: Options<PostSecurityQuotesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecurityQuotesResponses,
    PostSecurityQuotesErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-quotes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteSecurityQuotesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecurityQuotesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecurityQuotesByIdResponses,
    DeleteSecurityQuotesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-quotes/{id}', ...options });

export const getSecurityQuotesById = <ThrowOnError extends boolean = false>(
  options: Options<GetSecurityQuotesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecurityQuotesByIdResponses,
    GetSecurityQuotesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-quotes/{id}', ...options });

export const putSecurityQuotesById = <ThrowOnError extends boolean = false>(
  options: Options<PutSecurityQuotesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecurityQuotesByIdResponses,
    PutSecurityQuotesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-quotes/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getTransactionCashFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetTransactionCashFlowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetTransactionCashFlowsResponses,
    GetTransactionCashFlowsErrors,
    ThrowOnError
  >({ url: '/api/v1/transaction-cash-flows', ...options });

export const postTransactionCashFlows = <ThrowOnError extends boolean = false>(
  options: Options<PostTransactionCashFlowsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostTransactionCashFlowsResponses,
    PostTransactionCashFlowsErrors,
    ThrowOnError
  >({
    url: '/api/v1/transaction-cash-flows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Removes cash flow information for the transaction, the transaction itself is not deleted
 */
export const deleteTransactionCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTransactionCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTransactionCashFlowsByIdResponses,
    DeleteTransactionCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transaction-cash-flows/{id}', ...options });

export const getTransactionCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTransactionCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTransactionCashFlowsByIdResponses,
    GetTransactionCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transaction-cash-flows/{id}', ...options });

export const putTransactionCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutTransactionCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutTransactionCashFlowsByIdResponses,
    PutTransactionCashFlowsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/transaction-cash-flows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<GetTransactionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetTransactionsResponses,
    GetTransactionsErrors,
    ThrowOnError
  >({ url: '/api/v1/transactions', ...options });

export const postTransactions = <ThrowOnError extends boolean = false>(
  options: Options<PostTransactionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostTransactionsResponses,
    PostTransactionsErrors,
    ThrowOnError
  >({
    url: '/api/v1/transactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteTransactionsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTransactionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTransactionsByIdResponses,
    DeleteTransactionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transactions/{id}', ...options });

export const getTransactionsById = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTransactionsByIdResponses,
    GetTransactionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transactions/{id}', ...options });

export const putTransactionsById = <ThrowOnError extends boolean = false>(
  options: Options<PutTransactionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutTransactionsByIdResponses,
    PutTransactionsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Shutdown app
 */
export const postAppShutdown = <ThrowOnError extends boolean = false>(
  options?: Options<PostAppShutdownData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostAppShutdownResponses,
    PostAppShutdownErrors,
    ThrowOnError
  >({ url: '/app/shutdown', ...options });

/**
 * Get portfolio
 */
export const getPortfolioOpenFormatRecords = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetPortfolioOpenFormatRecordsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetPortfolioOpenFormatRecordsResponses,
    GetPortfolioOpenFormatRecordsErrors,
    ThrowOnError
  >({ url: '/portfolio-open-format/records', ...options });

/**
 * Upload portfolio
 */
export const postPortfolioOpenFormatRecords = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostPortfolioOpenFormatRecordsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPortfolioOpenFormatRecordsResponses,
    PostPortfolioOpenFormatRecordsErrors,
    ThrowOnError
  >({
    url: '/portfolio-open-format/records',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
