// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:2030' | (string & {});
};

export type Account = {
  /**
   * Active account flag: if false, the account is archived
   */
  enabled: boolean;
  /**
   * Account number in the broker's accounting system
   */
  id: string;
};

export type AccountCash = {
  /**
   * Account number in the broker's accounting system
   */
  account: string;
  /**
   * Currency
   */
  currency: string;
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Market
   */
  market: string;
  /**
   * Date and time
   */
  timestamp: string;
  /**
   * Cash balance
   */
  value: number;
};

export type AccountPof = {
  accountNumber?: string;
  id?: number;
  type: 'investment' | 'bank' | 'savings';
  valuation: number;
  valuationCurrency: string;
};

export type AccountProperty = {
  /**
   * Account number in the broker's accounting system
   */
  account: string;
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Property
   */
  property: 'TOTAL_ASSETS_RUB' | 'TOTAL_ASSETS_USD';
  /**
   * Date and time
   */
  timestamp?: string | null;
  /**
   * Value
   */
  value: string;
};

export type AccountStats = {
  accounts?: Array<string>;
  assetsValue?: number;
  cashBalance?: number;
  totalTransactions?: number;
};

export type AssetPof = {
  id?: number;
  isin?: string;
  name?: string;
  symbol?: string;
  type: string;
};

export type CashBalancesPof = {
  account?: number;
  cash: Array<CashPof>;
};

export type CashFlowPof = {
  account?: number;
  amount: number;
  currency: string;
  description?: string;
  flowId?: string;
  id?: number;
  timestamp?: number;
  type:
    | 'cash'
    | 'dividend'
    | 'coupon'
    | 'bond-amortization'
    | 'bond-redemption'
    | 'variation-margin'
    | 'fee'
    | 'tax'
    | 'interest'
    | 'other';
};

export type CashPof = {
  currency: string;
  value: number;
};

/**
 * Cash deposits and withdrawals, taxes, fees, and payouts on instruments from another account
 */
export type EventCashFlow = {
  /**
   * Account number in the broker's accounting system
   */
  account: string;
  /**
   * Currency
   */
  currency?: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Event type
   */
  eventType:
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Event time
   */
  timestamp: string;
  /**
   * Amount
   */
  value: number;
};

export type ForeignExchangeRate = {
  /**
   * Currency pair
   */
  currencyPair: string;
  /**
   * Date
   */
  date: string;
  /**
   * Currency exchange rate
   */
  rate: number;
};

export type Issuer = {
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Issuer name
   */
  name: string;
  /**
   * Taxpayer identification number (Russia: INN, US: EIN, etc.)
   */
  taxpayerId?: string | null;
};

export type Link = {
  href?: string;
  templated?: boolean;
};

export type PageAccount = {
  content?: Array<Account>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageAccountCash = {
  content?: Array<AccountCash>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageAccountProperty = {
  content?: Array<AccountProperty>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageEventCashFlow = {
  content?: Array<EventCashFlow>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageForeignExchangeRate = {
  content?: Array<ForeignExchangeRate>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageIssuer = {
  content?: Array<Issuer>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageSecurity = {
  content?: Array<Security>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageSecurityDescription = {
  content?: Array<SecurityDescription>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageSecurityEventCashFlow = {
  content?: Array<SecurityEventCashFlow>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageSecurityQuote = {
  content?: Array<SecurityQuote>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageTransaction = {
  content?: Array<Transaction>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageTransactionCashFlow = {
  content?: Array<TransactionCashFlow>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
};

export type PageableObject = {
  offset?: number;
  pageNumber?: number;
  pageSize?: number;
  paged?: boolean;
  sort?: SortObject;
  unpaged?: boolean;
};

export type PaymentPof = {
  account?: number;
  amount: number;
  asset?: number;
  count: number;
  currency: string;
  description?: string;
  id?: number;
  paymentId?: string;
  tax?: number;
  taxCurrency?: string;
  timestamp?: number;
  type:
    | 'cash'
    | 'dividend'
    | 'coupon'
    | 'bond-amortization'
    | 'bond-redemption'
    | 'variation-margin'
    | 'fee'
    | 'tax'
    | 'interest'
    | 'other';
};

export type PortfolioOpenFormatV110 = {
  accounts: Array<AccountPof>;
  assets: Array<AssetPof>;
  cashBalances: Array<CashBalancesPof>;
  cashFlows: Array<CashFlowPof>;
  end?: number;
  generated?: number;
  generatedBy: string;
  payments: Array<PaymentPof>;
  start?: number;
  trades: Array<TradePof>;
  transfers: Array<TransferPof>;
  version: string;
  vndInvestbook?: VndInvestbookPof;
};

/**
 * Stocks, bonds, futures, options, currency pairs and custom assets
 */
export type Security = {
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * ISIN of stocks and bonds
   */
  isin?: string | null;
  /**
   * Asset name
   */
  name?: string | null;
  /**
   * Ticker
   */
  ticker?: string | null;
  /**
   * Security type
   */
  type:
    | 'STOCK'
    | 'BOND'
    | 'STOCK_OR_BOND'
    | 'DERIVATIVE'
    | 'CURRENCY_PAIR'
    | 'ASSET';
};

export type SecurityDescription = {
  /**
   * Issuer record ID
   */
  issuer?: number | null;
  /**
   * Industry sector
   */
  sector?: string | null;
  /**
   * Security record ID
   */
  security: number;
};

/**
 * Dividends, coupons, amortizations, variation margin, taxes, fees
 */
export type SecurityEventCashFlow = {
  /**
   * Account number in the broker's accounting system
   */
  account: string;
  /**
   * Number of securities (contracts)
   */
  count: number;
  /**
   * Currency
   */
  currency?: string | null;
  /**
   * Event type
   */
  eventType:
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Security
   */
  security: number;
  /**
   * Event time
   */
  timestamp: string;
  /**
   * Amount
   */
  value: number;
};

/**
 * Quotes for traded instruments and valuations for custom assets
 */
export type SecurityQuote = {
  /**
   * Accrued coupon interest (in currency, for bonds only)
   */
  accruedInterest?: number | null;
  /**
   * Quote currency for stocks, bonds, and custom assets and optionally for derivatives
   */
  currency?: string | null;
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Quote in currency (for bonds and derivatives only)
   */
  price?: number | null;
  /**
   * Quote (for bonds - in percent, for derivatives - in points)
   */
  quote: number;
  /**
   * Asset
   */
  security: number;
  /**
   * Date and time
   */
  timestamp: string;
};

export type SortObject = {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
};

export type TradePof = {
  account?: number;
  accruedInterest?: number;
  asset?: number;
  count: number;
  currency?: string;
  description?: string;
  fee: number;
  feeCurrency: string;
  id?: number;
  price?: number;
  quote?: number;
  settlement?: number;
  timestamp?: number;
  tradeId: string;
};

export type Transaction = {
  /**
   * Account number in the broker's accounting system
   */
  account: string;
  /**
   * Number of securities (contracts)
   */
  count: number;
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Security
   */
  security: number;
  /**
   * Trade date and time
   */
  timestamp: string;
  /**
   * Trade ID in the broker's accounting system
   */
  tradeId: string;
};

export type TransactionCashFlow = {
  /**
   * Currency
   */
  currency?: string | null;
  /**
   * Event type
   */
  eventType:
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
  /**
   * Record ID
   */
  id?: number | null;
  /**
   * Transaction record ID
   */
  transactionId: number;
  /**
   * Transaction amount
   */
  value: number;
};

export type TransferPof = {
  account?: number;
  asset?: number;
  count: number;
  description?: string;
  fee?: number;
  feeAccount?: number;
  feeCurrency?: string;
  id?: number;
  timestamp?: number;
  transferId?: string;
};

export type VndInvestbookPof = {
  accountCash: Array<AccountCash>;
  accountProperties: Array<AccountProperty>;
  securityDescriptions: Array<SecurityDescription>;
  securityQuotes: Array<SecurityQuote>;
  version: string;
};

export type GetAccountsAllStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/accounts/all/stats';
};

export type GetAccountsAllStatsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountsAllStatsResponses = {
  /**
   * OK
   */
  200: AccountStats;
};

export type GetAccountsAllStatsResponse =
  GetAccountsAllStatsResponses[keyof GetAccountsAllStatsResponses];

export type GetActuatorData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/actuator';
};

export type GetActuatorResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: {
      [key: string]: Link;
    };
  };
};

export type GetActuatorResponse =
  GetActuatorResponses[keyof GetActuatorResponses];

export type GetActuatorConfigpropsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/actuator/configprops';
};

export type GetActuatorConfigpropsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetActuatorConfigpropsResponse =
  GetActuatorConfigpropsResponses[keyof GetActuatorConfigpropsResponses];

export type GetActuatorConfigpropsByPrefixData = {
  body?: never;
  path: {
    prefix: string;
  };
  query?: never;
  url: '/actuator/configprops/{prefix}';
};

export type GetActuatorConfigpropsByPrefixErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetActuatorConfigpropsByPrefixResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetActuatorConfigpropsByPrefixResponse =
  GetActuatorConfigpropsByPrefixResponses[keyof GetActuatorConfigpropsByPrefixResponses];

export type GetActuatorHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/actuator/health';
};

export type GetActuatorHealthResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetActuatorHealthResponse =
  GetActuatorHealthResponses[keyof GetActuatorHealthResponses];

export type GetActuatorInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/actuator/info';
};

export type GetActuatorInfoResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetActuatorInfoResponse =
  GetActuatorInfoResponses[keyof GetActuatorInfoResponses];

export type GetAccountCashData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    account?: string;
    timestamp?: string;
    market?: string;
    value?: number;
    currency?: string;
  };
  url: '/api/v1/account-cash';
};

export type GetAccountCashErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountCashResponses = {
  /**
   * OK
   */
  200: PageAccountCash;
};

export type GetAccountCashResponse =
  GetAccountCashResponses[keyof GetAccountCashResponses];

export type PostAccountCashData = {
  body: AccountCash;
  path?: never;
  query?: never;
  url: '/api/v1/account-cash';
};

export type PostAccountCashErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostAccountCashResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteAccountCashByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/account-cash/{id}';
};

export type DeleteAccountCashByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteAccountCashByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAccountCashByIdResponse =
  DeleteAccountCashByIdResponses[keyof DeleteAccountCashByIdResponses];

export type GetAccountCashByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/account-cash/{id}';
};

export type GetAccountCashByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountCashByIdResponses = {
  /**
   * OK
   */
  200: AccountCash;
};

export type GetAccountCashByIdResponse =
  GetAccountCashByIdResponses[keyof GetAccountCashByIdResponses];

export type PutAccountCashByIdData = {
  body: AccountCash;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/account-cash/{id}';
};

export type PutAccountCashByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutAccountCashByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutAccountCashByIdResponse =
  PutAccountCashByIdResponses[keyof PutAccountCashByIdResponses];

export type GetAccountPropertiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    account?: string;
    timestamp?: string;
    property?: string;
    value?: string;
  };
  url: '/api/v1/account-properties';
};

export type GetAccountPropertiesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountPropertiesResponses = {
  /**
   * OK
   */
  200: PageAccountProperty;
};

export type GetAccountPropertiesResponse =
  GetAccountPropertiesResponses[keyof GetAccountPropertiesResponses];

export type PostAccountPropertiesData = {
  body: AccountProperty;
  path?: never;
  query?: never;
  url: '/api/v1/account-properties';
};

export type PostAccountPropertiesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostAccountPropertiesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteAccountPropertiesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/account-properties/{id}';
};

export type DeleteAccountPropertiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteAccountPropertiesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAccountPropertiesByIdResponse =
  DeleteAccountPropertiesByIdResponses[keyof DeleteAccountPropertiesByIdResponses];

export type GetAccountPropertiesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/account-properties/{id}';
};

export type GetAccountPropertiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountPropertiesByIdResponses = {
  /**
   * OK
   */
  200: AccountProperty;
};

export type GetAccountPropertiesByIdResponse =
  GetAccountPropertiesByIdResponses[keyof GetAccountPropertiesByIdResponses];

export type PutAccountPropertiesByIdData = {
  body: AccountProperty;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/account-properties/{id}';
};

export type PutAccountPropertiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutAccountPropertiesByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutAccountPropertiesByIdResponse =
  PutAccountPropertiesByIdResponses[keyof PutAccountPropertiesByIdResponses];

export type GetAccountsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: string;
    enabled?: boolean;
  };
  url: '/api/v1/accounts';
};

export type GetAccountsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountsResponses = {
  /**
   * OK
   */
  200: PageAccount;
};

export type GetAccountsResponse =
  GetAccountsResponses[keyof GetAccountsResponses];

export type PostAccountsData = {
  body: Account;
  path?: never;
  query?: never;
  url: '/api/v1/accounts';
};

export type PostAccountsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostAccountsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteAccountsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{id}';
};

export type DeleteAccountsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteAccountsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAccountsByIdResponse =
  DeleteAccountsByIdResponses[keyof DeleteAccountsByIdResponses];

export type GetAccountsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{id}';
};

export type GetAccountsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetAccountsByIdResponses = {
  /**
   * OK
   */
  200: Account;
};

export type GetAccountsByIdResponse =
  GetAccountsByIdResponses[keyof GetAccountsByIdResponses];

export type PutAccountsByIdData = {
  body: Account;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/accounts/{id}';
};

export type PutAccountsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutAccountsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutAccountsByIdResponse =
  PutAccountsByIdResponses[keyof PutAccountsByIdResponses];

export type GetCashFlowTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/cash-flow-types';
};

export type GetCashFlowTypesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetCashFlowTypesResponses = {
  /**
   * OK
   */
  200: Array<
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE'
  >;
};

export type GetCashFlowTypesResponse =
  GetCashFlowTypesResponses[keyof GetCashFlowTypesResponses];

export type GetCashFlowTypesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/cash-flow-types/{id}';
};

export type GetCashFlowTypesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetCashFlowTypesByIdResponses = {
  /**
   * OK
   */
  200:
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
};

export type GetCashFlowTypesByIdResponse =
  GetCashFlowTypesByIdResponses[keyof GetCashFlowTypesByIdResponses];

export type GetEventCashFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    account?: string;
    timestamp?: string;
    cashFlowType?: string;
    value?: number;
    currency?: string;
    description?: string;
  };
  url: '/api/v1/event-cash-flows';
};

export type GetEventCashFlowsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetEventCashFlowsResponses = {
  /**
   * OK
   */
  200: PageEventCashFlow;
};

export type GetEventCashFlowsResponse =
  GetEventCashFlowsResponses[keyof GetEventCashFlowsResponses];

export type PostEventCashFlowsData = {
  body: EventCashFlow;
  path?: never;
  query?: never;
  url: '/api/v1/event-cash-flows';
};

export type PostEventCashFlowsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostEventCashFlowsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteEventCashFlowsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/event-cash-flows/{id}';
};

export type DeleteEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteEventCashFlowsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteEventCashFlowsByIdResponse =
  DeleteEventCashFlowsByIdResponses[keyof DeleteEventCashFlowsByIdResponses];

export type GetEventCashFlowsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/event-cash-flows/{id}';
};

export type GetEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetEventCashFlowsByIdResponses = {
  /**
   * OK
   */
  200: EventCashFlow;
};

export type GetEventCashFlowsByIdResponse =
  GetEventCashFlowsByIdResponses[keyof GetEventCashFlowsByIdResponses];

export type PutEventCashFlowsByIdData = {
  body: EventCashFlow;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/event-cash-flows/{id}';
};

export type PutEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutEventCashFlowsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutEventCashFlowsByIdResponse =
  PutEventCashFlowsByIdResponses[keyof PutEventCashFlowsByIdResponses];

export type GetForeignExchangeRatesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    pk?: string;
    rate?: number;
  };
  url: '/api/v1/foreign-exchange-rates';
};

export type GetForeignExchangeRatesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetForeignExchangeRatesResponses = {
  /**
   * OK
   */
  200: PageForeignExchangeRate;
};

export type GetForeignExchangeRatesResponse =
  GetForeignExchangeRatesResponses[keyof GetForeignExchangeRatesResponses];

export type PostForeignExchangeRatesData = {
  body: ForeignExchangeRate;
  path?: never;
  query?: never;
  url: '/api/v1/foreign-exchange-rates';
};

export type PostForeignExchangeRatesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostForeignExchangeRatesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairData = {
  body?: never;
  path: {
    currencyPair: string;
  };
  query?: never;
  url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}';
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses = {
  /**
   * OK
   */
  200: Array<ForeignExchangeRate>;
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponse =
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses[keyof GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses];

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData =
  {
    body?: never;
    path: {
      currencyPair: string;
      date: string;
    };
    query?: never;
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}/dates/{date}';
  };

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors =
  {
    /**
     * Internal Server Error
     */
    500: unknown;
  };

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses =
  {
    /**
     * No Content
     */
    204: void;
  };

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponse =
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses[keyof DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses];

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData =
  {
    body?: never;
    path: {
      currencyPair: string;
      date: string;
    };
    query?: never;
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}/dates/{date}';
  };

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors =
  {
    /**
     * Internal Server Error
     */
    500: unknown;
  };

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses =
  {
    /**
     * OK
     */
    200: ForeignExchangeRate;
  };

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponse =
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses[keyof GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses];

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData =
  {
    body: ForeignExchangeRate;
    path: {
      currencyPair: string;
      date: string;
    };
    query?: never;
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currencyPair}/dates/{date}';
  };

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors =
  {
    /**
     * Internal Server Error
     */
    500: unknown;
  };

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses =
  {
    /**
     * Created
     */
    201: unknown;
    /**
     * No Content
     */
    204: void;
  };

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponse =
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses[keyof PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses];

export type GetIssuersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    taxpayerId?: string;
    name?: string;
  };
  url: '/api/v1/issuers';
};

export type GetIssuersErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetIssuersResponses = {
  /**
   * OK
   */
  200: PageIssuer;
};

export type GetIssuersResponse = GetIssuersResponses[keyof GetIssuersResponses];

export type PostIssuersData = {
  body: Issuer;
  path?: never;
  query?: never;
  url: '/api/v1/issuers';
};

export type PostIssuersErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostIssuersResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteIssuersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/issuers/{id}';
};

export type DeleteIssuersByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteIssuersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteIssuersByIdResponse =
  DeleteIssuersByIdResponses[keyof DeleteIssuersByIdResponses];

export type GetIssuersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/issuers/{id}';
};

export type GetIssuersByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetIssuersByIdResponses = {
  /**
   * OK
   */
  200: Issuer;
};

export type GetIssuersByIdResponse =
  GetIssuersByIdResponses[keyof GetIssuersByIdResponses];

export type PutIssuersByIdData = {
  body: Issuer;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/issuers/{id}';
};

export type PutIssuersByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutIssuersByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutIssuersByIdResponse =
  PutIssuersByIdResponses[keyof PutIssuersByIdResponses];

export type GetSecuritiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    type?:
      | 'STOCK'
      | 'BOND'
      | 'STOCK_OR_BOND'
      | 'DERIVATIVE'
      | 'CURRENCY_PAIR'
      | 'ASSET';
    isin?: string;
    ticker?: string;
    name?: string;
  };
  url: '/api/v1/securities';
};

export type GetSecuritiesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecuritiesResponses = {
  /**
   * OK
   */
  200: PageSecurity;
};

export type GetSecuritiesResponse =
  GetSecuritiesResponses[keyof GetSecuritiesResponses];

export type PostSecuritiesData = {
  body: Security;
  path?: never;
  query?: never;
  url: '/api/v1/securities';
};

export type PostSecuritiesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecuritiesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteSecuritiesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/securities/{id}';
};

export type DeleteSecuritiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecuritiesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecuritiesByIdResponse =
  DeleteSecuritiesByIdResponses[keyof DeleteSecuritiesByIdResponses];

export type GetSecuritiesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/securities/{id}';
};

export type GetSecuritiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecuritiesByIdResponses = {
  /**
   * OK
   */
  200: Security;
};

export type GetSecuritiesByIdResponse =
  GetSecuritiesByIdResponses[keyof GetSecuritiesByIdResponses];

export type PutSecuritiesByIdData = {
  body: Security;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/securities/{id}';
};

export type PutSecuritiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecuritiesByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecuritiesByIdResponse =
  PutSecuritiesByIdResponses[keyof PutSecuritiesByIdResponses];

export type GetSecurityDescriptionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    security?: number;
    sector?: string;
    issuer?: string;
  };
  url: '/api/v1/security-descriptions';
};

export type GetSecurityDescriptionsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityDescriptionsResponses = {
  /**
   * OK
   */
  200: PageSecurityDescription;
};

export type GetSecurityDescriptionsResponse =
  GetSecurityDescriptionsResponses[keyof GetSecurityDescriptionsResponses];

export type PostSecurityDescriptionsData = {
  body: SecurityDescription;
  path?: never;
  query?: never;
  url: '/api/v1/security-descriptions';
};

export type PostSecurityDescriptionsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecurityDescriptionsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteSecurityDescriptionsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-descriptions/{id}';
};

export type DeleteSecurityDescriptionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecurityDescriptionsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecurityDescriptionsByIdResponse =
  DeleteSecurityDescriptionsByIdResponses[keyof DeleteSecurityDescriptionsByIdResponses];

export type GetSecurityDescriptionsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-descriptions/{id}';
};

export type GetSecurityDescriptionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityDescriptionsByIdResponses = {
  /**
   * OK
   */
  200: SecurityDescription;
};

export type GetSecurityDescriptionsByIdResponse =
  GetSecurityDescriptionsByIdResponses[keyof GetSecurityDescriptionsByIdResponses];

export type PutSecurityDescriptionsByIdData = {
  body: SecurityDescription;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-descriptions/{id}';
};

export type PutSecurityDescriptionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecurityDescriptionsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecurityDescriptionsByIdResponse =
  PutSecurityDescriptionsByIdResponses[keyof PutSecurityDescriptionsByIdResponses];

export type GetSecurityEventCashFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    account?: string;
    timestamp?: string;
    security?: string;
    count?: number;
    cashFlowType?: string;
    value?: number;
    currency?: string;
  };
  url: '/api/v1/security-event-cash-flows';
};

export type GetSecurityEventCashFlowsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityEventCashFlowsResponses = {
  /**
   * OK
   */
  200: PageSecurityEventCashFlow;
};

export type GetSecurityEventCashFlowsResponse =
  GetSecurityEventCashFlowsResponses[keyof GetSecurityEventCashFlowsResponses];

export type PostSecurityEventCashFlowsData = {
  body: SecurityEventCashFlow;
  path?: never;
  query?: never;
  url: '/api/v1/security-event-cash-flows';
};

export type PostSecurityEventCashFlowsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecurityEventCashFlowsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteSecurityEventCashFlowsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-event-cash-flows/{id}';
};

export type DeleteSecurityEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecurityEventCashFlowsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecurityEventCashFlowsByIdResponse =
  DeleteSecurityEventCashFlowsByIdResponses[keyof DeleteSecurityEventCashFlowsByIdResponses];

export type GetSecurityEventCashFlowsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-event-cash-flows/{id}';
};

export type GetSecurityEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityEventCashFlowsByIdResponses = {
  /**
   * OK
   */
  200: SecurityEventCashFlow;
};

export type GetSecurityEventCashFlowsByIdResponse =
  GetSecurityEventCashFlowsByIdResponses[keyof GetSecurityEventCashFlowsByIdResponses];

export type PutSecurityEventCashFlowsByIdData = {
  body: SecurityEventCashFlow;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-event-cash-flows/{id}';
};

export type PutSecurityEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecurityEventCashFlowsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecurityEventCashFlowsByIdResponse =
  PutSecurityEventCashFlowsByIdResponses[keyof PutSecurityEventCashFlowsByIdResponses];

export type GetSecurityQuotesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    security?: string;
    timestamp?: string;
    quote?: number;
    price?: number;
    accruedInterest?: number;
    currency?: string;
  };
  url: '/api/v1/security-quotes';
};

export type GetSecurityQuotesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityQuotesResponses = {
  /**
   * OK
   */
  200: PageSecurityQuote;
};

export type GetSecurityQuotesResponse =
  GetSecurityQuotesResponses[keyof GetSecurityQuotesResponses];

export type PostSecurityQuotesData = {
  body: SecurityQuote;
  path?: never;
  query?: never;
  url: '/api/v1/security-quotes';
};

export type PostSecurityQuotesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecurityQuotesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteSecurityQuotesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-quotes/{id}';
};

export type DeleteSecurityQuotesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecurityQuotesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecurityQuotesByIdResponse =
  DeleteSecurityQuotesByIdResponses[keyof DeleteSecurityQuotesByIdResponses];

export type GetSecurityQuotesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-quotes/{id}';
};

export type GetSecurityQuotesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityQuotesByIdResponses = {
  /**
   * OK
   */
  200: SecurityQuote;
};

export type GetSecurityQuotesByIdResponse =
  GetSecurityQuotesByIdResponses[keyof GetSecurityQuotesByIdResponses];

export type PutSecurityQuotesByIdData = {
  body: SecurityQuote;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/security-quotes/{id}';
};

export type PutSecurityQuotesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecurityQuotesByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecurityQuotesByIdResponse =
  PutSecurityQuotesByIdResponses[keyof PutSecurityQuotesByIdResponses];

export type GetTransactionCashFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Type (price / fee / accrued interest)
     */
    'event-type'?: number;
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    transactionId?: number;
    cashFlowType?: string;
    value?: number;
    currency?: string;
  };
  url: '/api/v1/transaction-cash-flows';
};

export type GetTransactionCashFlowsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionCashFlowsResponses = {
  /**
   * OK
   */
  200: PageTransactionCashFlow;
};

export type GetTransactionCashFlowsResponse =
  GetTransactionCashFlowsResponses[keyof GetTransactionCashFlowsResponses];

export type PostTransactionCashFlowsData = {
  body: TransactionCashFlow;
  path?: never;
  query?: never;
  url: '/api/v1/transaction-cash-flows';
};

export type PostTransactionCashFlowsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostTransactionCashFlowsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteTransactionCashFlowsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/transaction-cash-flows/{id}';
};

export type DeleteTransactionCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteTransactionCashFlowsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteTransactionCashFlowsByIdResponse =
  DeleteTransactionCashFlowsByIdResponses[keyof DeleteTransactionCashFlowsByIdResponses];

export type GetTransactionCashFlowsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/transaction-cash-flows/{id}';
};

export type GetTransactionCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionCashFlowsByIdResponses = {
  /**
   * OK
   */
  200: TransactionCashFlow;
};

export type GetTransactionCashFlowsByIdResponse =
  GetTransactionCashFlowsByIdResponses[keyof GetTransactionCashFlowsByIdResponses];

export type PutTransactionCashFlowsByIdData = {
  body: TransactionCashFlow;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/transaction-cash-flows/{id}';
};

export type PutTransactionCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutTransactionCashFlowsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutTransactionCashFlowsByIdResponse =
  PutTransactionCashFlowsByIdResponses[keyof PutTransactionCashFlowsByIdResponses];

export type GetTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
    id?: number;
    tradeId?: string;
    account?: string;
    security?: string;
    timestamp?: string;
    count?: number;
  };
  url: '/api/v1/transactions';
};

export type GetTransactionsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionsResponses = {
  /**
   * OK
   */
  200: PageTransaction;
};

export type GetTransactionsResponse =
  GetTransactionsResponses[keyof GetTransactionsResponses];

export type PostTransactionsData = {
  body: Transaction;
  path?: never;
  query?: never;
  url: '/api/v1/transactions';
};

export type PostTransactionsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostTransactionsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteTransactionsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/transactions/{id}';
};

export type DeleteTransactionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteTransactionsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteTransactionsByIdResponse =
  DeleteTransactionsByIdResponses[keyof DeleteTransactionsByIdResponses];

export type GetTransactionsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/transactions/{id}';
};

export type GetTransactionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionsByIdResponses = {
  /**
   * OK
   */
  200: Transaction;
};

export type GetTransactionsByIdResponse =
  GetTransactionsByIdResponses[keyof GetTransactionsByIdResponses];

export type PutTransactionsByIdData = {
  body: Transaction;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/transactions/{id}';
};

export type PutTransactionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutTransactionsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutTransactionsByIdResponse =
  PutTransactionsByIdResponses[keyof PutTransactionsByIdResponses];

export type PostAppShutdownData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/app/shutdown';
};

export type PostAppShutdownErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostAppShutdownResponses = {
  /**
   * Accepted
   */
  202: unknown;
};

export type GetPortfolioOpenFormatRecordsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/portfolio-open-format/records';
};

export type GetPortfolioOpenFormatRecordsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfolioOpenFormatRecordsResponses = {
  /**
   * OK
   */
  200: PortfolioOpenFormatV110;
};

export type GetPortfolioOpenFormatRecordsResponse =
  GetPortfolioOpenFormatRecordsResponses[keyof GetPortfolioOpenFormatRecordsResponses];

export type PostPortfolioOpenFormatRecordsData = {
  body: PortfolioOpenFormatV110;
  path?: never;
  query?: never;
  url: '/portfolio-open-format/records';
};

export type PostPortfolioOpenFormatRecordsErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostPortfolioOpenFormatRecordsResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostPortfolioOpenFormatRecordsResponse =
  PostPortfolioOpenFormatRecordsResponses[keyof PostPortfolioOpenFormatRecordsResponses];
