// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteEventCashFlowsByIdData,
  DeleteEventCashFlowsByIdErrors,
  DeleteEventCashFlowsByIdResponses,
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
  DeleteIssuersByIdData,
  DeleteIssuersByIdErrors,
  DeleteIssuersByIdResponses,
  DeletePortfolioCashByIdData,
  DeletePortfolioCashByIdErrors,
  DeletePortfolioCashByIdResponses,
  DeletePortfolioPropertiesByIdData,
  DeletePortfolioPropertiesByIdErrors,
  DeletePortfolioPropertiesByIdResponses,
  DeletePortfoliosByIdData,
  DeletePortfoliosByIdErrors,
  DeletePortfoliosByIdResponses,
  DeleteSecuritiesByIdData,
  DeleteSecuritiesByIdErrors,
  DeleteSecuritiesByIdResponses,
  DeleteSecurityDescriptionsByIdData,
  DeleteSecurityDescriptionsByIdErrors,
  DeleteSecurityDescriptionsByIdResponses,
  DeleteSecurityEventCashFlowsByIdData,
  DeleteSecurityEventCashFlowsByIdErrors,
  DeleteSecurityEventCashFlowsByIdResponses,
  DeleteSecurityQuotesByIdData,
  DeleteSecurityQuotesByIdErrors,
  DeleteSecurityQuotesByIdResponses,
  DeleteTransactionCashFlowsByIdData,
  DeleteTransactionCashFlowsByIdErrors,
  DeleteTransactionCashFlowsByIdResponses,
  DeleteTransactionsByIdData,
  DeleteTransactionsByIdErrors,
  DeleteTransactionsByIdResponses,
  GetCashFlowTypesByIdData,
  GetCashFlowTypesByIdErrors,
  GetCashFlowTypesByIdResponses,
  GetCashFlowTypesData,
  GetCashFlowTypesErrors,
  GetCashFlowTypesResponses,
  GetEventCashFlowsByIdData,
  GetEventCashFlowsByIdErrors,
  GetEventCashFlowsByIdResponses,
  GetEventCashFlowsData,
  GetEventCashFlowsErrors,
  GetEventCashFlowsResponses,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairData,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairErrors,
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses,
  GetForeignExchangeRatesData,
  GetForeignExchangeRatesErrors,
  GetForeignExchangeRatesResponses,
  GetIssuersByIdData,
  GetIssuersByIdErrors,
  GetIssuersByIdResponses,
  GetIssuersData,
  GetIssuersErrors,
  GetIssuersResponses,
  GetPortfolioCashByIdData,
  GetPortfolioCashByIdErrors,
  GetPortfolioCashByIdResponses,
  GetPortfolioCashData,
  GetPortfolioCashErrors,
  GetPortfolioCashResponses,
  GetPortfolioPropertiesByIdData,
  GetPortfolioPropertiesByIdErrors,
  GetPortfolioPropertiesByIdResponses,
  GetPortfolioPropertiesData,
  GetPortfolioPropertiesErrors,
  GetPortfolioPropertiesResponses,
  GetPortfoliosByIdData,
  GetPortfoliosByIdErrors,
  GetPortfoliosByIdResponses,
  GetPortfoliosData,
  GetPortfoliosErrors,
  GetPortfoliosResponses,
  GetSecuritiesByIdData,
  GetSecuritiesByIdErrors,
  GetSecuritiesByIdResponses,
  GetSecuritiesData,
  GetSecuritiesErrors,
  GetSecuritiesResponses,
  GetSecurityDescriptionsByIdData,
  GetSecurityDescriptionsByIdErrors,
  GetSecurityDescriptionsByIdResponses,
  GetSecurityDescriptionsData,
  GetSecurityDescriptionsErrors,
  GetSecurityDescriptionsResponses,
  GetSecurityEventCashFlowsByIdData,
  GetSecurityEventCashFlowsByIdErrors,
  GetSecurityEventCashFlowsByIdResponses,
  GetSecurityEventCashFlowsData,
  GetSecurityEventCashFlowsErrors,
  GetSecurityEventCashFlowsResponses,
  GetSecurityQuotesByIdData,
  GetSecurityQuotesByIdErrors,
  GetSecurityQuotesByIdResponses,
  GetSecurityQuotesData,
  GetSecurityQuotesErrors,
  GetSecurityQuotesResponses,
  GetTransactionCashFlowsByIdData,
  GetTransactionCashFlowsByIdErrors,
  GetTransactionCashFlowsByIdResponses,
  GetTransactionCashFlowsData,
  GetTransactionCashFlowsErrors,
  GetTransactionCashFlowsResponses,
  GetTransactionsByIdData,
  GetTransactionsByIdErrors,
  GetTransactionsByIdResponses,
  GetTransactionsData,
  GetTransactionsErrors,
  GetTransactionsResponses,
  PostEventCashFlowsData,
  PostEventCashFlowsErrors,
  PostEventCashFlowsResponses,
  PostForeignExchangeRatesData,
  PostForeignExchangeRatesErrors,
  PostForeignExchangeRatesResponses,
  PostIssuersData,
  PostIssuersErrors,
  PostIssuersResponses,
  PostPortfolioCashData,
  PostPortfolioCashErrors,
  PostPortfolioCashResponses,
  PostPortfolioPropertiesData,
  PostPortfolioPropertiesErrors,
  PostPortfolioPropertiesResponses,
  PostPortfoliosData,
  PostPortfoliosErrors,
  PostPortfoliosResponses,
  PostSecuritiesData,
  PostSecuritiesErrors,
  PostSecuritiesResponses,
  PostSecurityDescriptionsData,
  PostSecurityDescriptionsErrors,
  PostSecurityDescriptionsResponses,
  PostSecurityEventCashFlowsData,
  PostSecurityEventCashFlowsErrors,
  PostSecurityEventCashFlowsResponses,
  PostSecurityQuotesData,
  PostSecurityQuotesErrors,
  PostSecurityQuotesResponses,
  PostTransactionCashFlowsData,
  PostTransactionCashFlowsErrors,
  PostTransactionCashFlowsResponses,
  PostTransactionsData,
  PostTransactionsErrors,
  PostTransactionsResponses,
  PutEventCashFlowsByIdData,
  PutEventCashFlowsByIdErrors,
  PutEventCashFlowsByIdResponses,
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
  PutIssuersByIdData,
  PutIssuersByIdErrors,
  PutIssuersByIdResponses,
  PutPortfolioCashByIdData,
  PutPortfolioCashByIdErrors,
  PutPortfolioCashByIdResponses,
  PutPortfolioPropertiesByIdData,
  PutPortfolioPropertiesByIdErrors,
  PutPortfolioPropertiesByIdResponses,
  PutPortfoliosByIdData,
  PutPortfoliosByIdErrors,
  PutPortfoliosByIdResponses,
  PutSecuritiesByIdData,
  PutSecuritiesByIdErrors,
  PutSecuritiesByIdResponses,
  PutSecurityDescriptionsByIdData,
  PutSecurityDescriptionsByIdErrors,
  PutSecurityDescriptionsByIdResponses,
  PutSecurityEventCashFlowsByIdData,
  PutSecurityEventCashFlowsByIdErrors,
  PutSecurityEventCashFlowsByIdResponses,
  PutSecurityQuotesByIdData,
  PutSecurityQuotesByIdErrors,
  PutSecurityQuotesByIdResponses,
  PutTransactionCashFlowsByIdData,
  PutTransactionCashFlowsByIdErrors,
  PutTransactionCashFlowsByIdResponses,
  PutTransactionsByIdData,
  PutTransactionsByIdErrors,
  PutTransactionsByIdResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Удалить
 *
 * Удаляет указанную сделку
 */
export const deleteTransactionsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTransactionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTransactionsByIdResponses,
    DeleteTransactionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transactions/{id}', ...options });

/**
 * Отобразить одну
 *
 * Отображает одну сделку
 */
export const getTransactionsById = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTransactionsByIdResponses,
    GetTransactionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transactions/{id}', ...options });

/**
 * Обновить параметры
 *
 * Обновляет параметры указанной сделки
 */
export const putTransactionsById = <ThrowOnError extends boolean = false>(
  options: Options<PutTransactionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutTransactionsByIdResponses,
    PutTransactionsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удалить информацию об об объемах движения ДС по сделке. Сама сделка не удаляется, ее нужно удалить своим API
 *
 */
export const deleteTransactionCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTransactionCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTransactionCashFlowsByIdResponses,
    DeleteTransactionCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transaction-cash-flows/{id}', ...options });

/**
 * Отобразить одну
 *
 * Отобразить информацию о конкретной сделке
 */
export const getTransactionCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTransactionCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTransactionCashFlowsByIdResponses,
    GetTransactionCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/transaction-cash-flows/{id}', ...options });

/**
 * Обновить
 *
 * Обновить информацию об об объемах движения ДС по сделке
 */
export const putTransactionCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutTransactionCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutTransactionCashFlowsByIdResponses,
    PutTransactionCashFlowsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/transaction-cash-flows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 */
export const deleteSecurityQuotesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecurityQuotesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecurityQuotesByIdResponses,
    DeleteSecurityQuotesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-quotes/{id}', ...options });

/**
 * Отобразить одну
 *
 * Отобразить котировку по номеру записи
 */
export const getSecurityQuotesById = <ThrowOnError extends boolean = false>(
  options: Options<GetSecurityQuotesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecurityQuotesByIdResponses,
    GetSecurityQuotesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-quotes/{id}', ...options });

/**
 * Обновить
 */
export const putSecurityQuotesById = <ThrowOnError extends boolean = false>(
  options: Options<PutSecurityQuotesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecurityQuotesByIdResponses,
    PutSecurityQuotesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-quotes/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удалить информацию о выплате
 */
export const deleteSecurityEventCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSecurityEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecurityEventCashFlowsByIdResponses,
    DeleteSecurityEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-event-cash-flows/{id}', ...options });

/**
 * Отобразить одну
 *
 * Отобразить выплату по идентификатору
 */
export const getSecurityEventCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSecurityEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecurityEventCashFlowsByIdResponses,
    GetSecurityEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-event-cash-flows/{id}', ...options });

/**
 * Обновить
 *
 * Модифицировать информацию о выплате
 */
export const putSecurityEventCashFlowsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSecurityEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecurityEventCashFlowsByIdResponses,
    PutSecurityEventCashFlowsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-event-cash-flows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удалить информацию по инструменту
 */
export const deleteSecurityDescriptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSecurityDescriptionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecurityDescriptionsByIdResponses,
    DeleteSecurityDescriptionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-descriptions/{id}', ...options });

/**
 * Отобразить один
 *
 * Отобразить информацию по инструменту
 */
export const getSecurityDescriptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSecurityDescriptionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecurityDescriptionsByIdResponses,
    GetSecurityDescriptionsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/security-descriptions/{id}', ...options });

/**
 * Обновить
 *
 * Добавить информацию об акции, облигации, деривативе или валютной паре
 */
export const putSecurityDescriptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSecurityDescriptionsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecurityDescriptionsByIdResponses,
    PutSecurityDescriptionsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-descriptions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удалить сведения о биржевом инструменте и всех его сделках по всем счетам
 */
export const deleteSecuritiesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecuritiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecuritiesByIdResponses,
    DeleteSecuritiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/securities/{id}', ...options });

/**
 * Отобразить один
 *
 * Отобразить биржевой инструмент по внутреннему идентификатору
 */
export const getSecuritiesById = <ThrowOnError extends boolean = false>(
  options: Options<GetSecuritiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecuritiesByIdResponses,
    GetSecuritiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/securities/{id}', ...options });

/**
 * Обновить
 *
 * Добавить информацию об акции, облигации, деривативе или валютной паре
 */
export const putSecuritiesById = <ThrowOnError extends boolean = false>(
  options: Options<PutSecuritiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutSecuritiesByIdResponses,
    PutSecuritiesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/securities/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удалить счет и все связанные с ним данные
 */
export const deletePortfoliosById = <ThrowOnError extends boolean = false>(
  options: Options<DeletePortfoliosByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeletePortfoliosByIdResponses,
    DeletePortfoliosByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolios/{id}', ...options });

/**
 * Отобразить один
 */
export const getPortfoliosById = <ThrowOnError extends boolean = false>(
  options: Options<GetPortfoliosByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetPortfoliosByIdResponses,
    GetPortfoliosByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolios/{id}', ...options });

/**
 * Обновить
 */
export const putPortfoliosById = <ThrowOnError extends boolean = false>(
  options: Options<PutPortfoliosByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutPortfoliosByIdResponses,
    PutPortfoliosByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/portfolios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 */
export const deletePortfolioPropertiesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePortfolioPropertiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeletePortfolioPropertiesByIdResponses,
    DeletePortfolioPropertiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolio-properties/{id}', ...options });

/**
 * Отобразить один
 *
 * Отображает информацию по идентификатору
 */
export const getPortfolioPropertiesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPortfolioPropertiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetPortfolioPropertiesByIdResponses,
    GetPortfolioPropertiesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolio-properties/{id}', ...options });

/**
 * Обновить
 *
 * Обновить информацию для счета
 */
export const putPortfolioPropertiesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutPortfolioPropertiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutPortfolioPropertiesByIdResponses,
    PutPortfolioPropertiesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/portfolio-properties/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 */
export const deletePortfolioCashById = <ThrowOnError extends boolean = false>(
  options: Options<DeletePortfolioCashByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeletePortfolioCashByIdResponses,
    DeletePortfolioCashByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolio-cash/{id}', ...options });

/**
 * Отобразить один
 *
 * Отображает информацию по идентификатору
 */
export const getPortfolioCashById = <ThrowOnError extends boolean = false>(
  options: Options<GetPortfolioCashByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetPortfolioCashByIdResponses,
    GetPortfolioCashByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolio-cash/{id}', ...options });

/**
 * Обновить
 *
 * Обновить информацию для счета
 */
export const putPortfolioCashById = <ThrowOnError extends boolean = false>(
  options: Options<PutPortfolioCashByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutPortfolioCashByIdResponses,
    PutPortfolioCashByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/portfolio-cash/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удаляет сведения об эмитенте из БД
 */
export const deleteIssuersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIssuersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteIssuersByIdResponses,
    DeleteIssuersByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/issuers/{id}', ...options });

/**
 * Отобразить одного
 *
 * Отобразить информацию об эмитенте по его номеру
 */
export const getIssuersById = <ThrowOnError extends boolean = false>(
  options: Options<GetIssuersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetIssuersByIdResponses,
    GetIssuersByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/issuers/{id}', ...options });

/**
 * Обновить сведения
 */
export const putIssuersById = <ThrowOnError extends boolean = false>(
  options: Options<PutIssuersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutIssuersByIdResponses,
    PutIssuersByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/issuers/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удаляет информацию о курсе из БД
 */
export const deleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDate =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
      ThrowOnError
    >,
  ) =>
    (options.client ?? client).delete<
      DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
      DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
      ThrowOnError
    >({
      url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}/dates/{date}',
      ...options,
    });

/**
 * Отобразить по валюте и дате
 */
export const getForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}/dates/{date}',
    ...options,
  });

/**
 * Обновить
 *
 * Обновляет информацию о курсе валюты за заданную дату
 */
export const putForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses,
    PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}/dates/{date}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить
 *
 * Удалить информацию из БД
 */
export const deleteEventCashFlowsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteEventCashFlowsByIdResponses,
    DeleteEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/event-cash-flows/{id}', ...options });

/**
 * Отобразить одну
 *
 * Отобразить выплату по ее номеру
 */
export const getEventCashFlowsById = <ThrowOnError extends boolean = false>(
  options: Options<GetEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEventCashFlowsByIdResponses,
    GetEventCashFlowsByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/event-cash-flows/{id}', ...options });

/**
 * Обновить
 *
 * Модифицировать информацию
 */
export const putEventCashFlowsById = <ThrowOnError extends boolean = false>(
  options: Options<PutEventCashFlowsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutEventCashFlowsByIdResponses,
    PutEventCashFlowsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/event-cash-flows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить по фильтру
 *
 * Отображает сделки по счетам
 */
export const getTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<GetTransactionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetTransactionsResponses,
    GetTransactionsErrors,
    ThrowOnError
  >({ url: '/api/v1/transactions', ...options });

/**
 * Добавить
 *
 * Сохраняет новую сделку
 */
export const postTransactions = <ThrowOnError extends boolean = false>(
  options: Options<PostTransactionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostTransactionsResponses,
    PostTransactionsErrors,
    ThrowOnError
  >({
    url: '/api/v1/transactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить по фильтру
 *
 * Отобразить информацию о сделках
 */
export const getTransactionCashFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetTransactionCashFlowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetTransactionCashFlowsResponses,
    GetTransactionCashFlowsErrors,
    ThrowOnError
  >({ url: '/api/v1/transaction-cash-flows', ...options });

/**
 * Добавить
 *
 * Добавить информацию об об объемах движения ДС по сделке
 */
export const postTransactionCashFlows = <ThrowOnError extends boolean = false>(
  options: Options<PostTransactionCashFlowsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostTransactionCashFlowsResponses,
    PostTransactionCashFlowsErrors,
    ThrowOnError
  >({
    url: '/api/v1/transaction-cash-flows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отобразить всю историю котировок по всем инструментам
 */
export const getSecurityQuotes = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecurityQuotesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecurityQuotesResponses,
    GetSecurityQuotesErrors,
    ThrowOnError
  >({ url: '/api/v1/security-quotes', ...options });

/**
 * Добавить
 */
export const postSecurityQuotes = <ThrowOnError extends boolean = false>(
  options: Options<PostSecurityQuotesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecurityQuotesResponses,
    PostSecurityQuotesErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-quotes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отображает все выплаты по всем счетам
 */
export const getSecurityEventCashFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecurityEventCashFlowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecurityEventCashFlowsResponses,
    GetSecurityEventCashFlowsErrors,
    ThrowOnError
  >({ url: '/api/v1/security-event-cash-flows', ...options });

/**
 * Добавить
 *
 * Сохранить информацию о выплате
 */
export const postSecurityEventCashFlows = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostSecurityEventCashFlowsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecurityEventCashFlowsResponses,
    PostSecurityEventCashFlowsErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-event-cash-flows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отобразить информацию по всем инструментам
 */
export const getSecurityDescriptions = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecurityDescriptionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecurityDescriptionsResponses,
    GetSecurityDescriptionsErrors,
    ThrowOnError
  >({ url: '/api/v1/security-descriptions', ...options });

/**
 * Добавить
 *
 * Добавить информацию об акции, облигации, деривативе или валютной паре
 */
export const postSecurityDescriptions = <ThrowOnError extends boolean = false>(
  options: Options<PostSecurityDescriptionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecurityDescriptionsResponses,
    PostSecurityDescriptionsErrors,
    ThrowOnError
  >({
    url: '/api/v1/security-descriptions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отобразить все биржевые инструменты
 */
export const getSecurities = <ThrowOnError extends boolean = false>(
  options?: Options<GetSecuritiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSecuritiesResponses,
    GetSecuritiesErrors,
    ThrowOnError
  >({ url: '/api/v1/securities', ...options });

/**
 * Добавить
 *
 * Добавить информацию об акции, облигации, деривативе или валютной паре
 */
export const postSecurities = <ThrowOnError extends boolean = false>(
  options: Options<PostSecuritiesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSecuritiesResponses,
    PostSecuritiesErrors,
    ThrowOnError
  >({
    url: '/api/v1/securities',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 */
export const getPortfolios = <ThrowOnError extends boolean = false>(
  options?: Options<GetPortfoliosData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetPortfoliosResponses,
    GetPortfoliosErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolios', ...options });

/**
 * Добавить
 */
export const postPortfolios = <ThrowOnError extends boolean = false>(
  options: Options<PostPortfoliosData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPortfoliosResponses,
    PostPortfoliosErrors,
    ThrowOnError
  >({
    url: '/api/v1/portfolios',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отображает всю имеющуюся информацию обо всех счетах
 */
export const getPortfolioProperties = <ThrowOnError extends boolean = false>(
  options?: Options<GetPortfolioPropertiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetPortfolioPropertiesResponses,
    GetPortfolioPropertiesErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolio-properties', ...options });

/**
 * Добавить
 *
 * Добавить информацию для конкретного счета
 */
export const postPortfolioProperties = <ThrowOnError extends boolean = false>(
  options: Options<PostPortfolioPropertiesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPortfolioPropertiesResponses,
    PostPortfolioPropertiesErrors,
    ThrowOnError
  >({
    url: '/api/v1/portfolio-properties',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отображает всю информацию обо всех счетах
 */
export const getPortfolioCash = <ThrowOnError extends boolean = false>(
  options?: Options<GetPortfolioCashData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetPortfolioCashResponses,
    GetPortfolioCashErrors,
    ThrowOnError
  >({ url: '/api/v1/portfolio-cash', ...options });

/**
 * Добавить
 *
 * Добавить информацию для конкретного счета
 */
export const postPortfolioCash = <ThrowOnError extends boolean = false>(
  options: Options<PostPortfolioCashData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPortfolioCashResponses,
    PostPortfolioCashErrors,
    ThrowOnError
  >({
    url: '/api/v1/portfolio-cash',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить всех
 */
export const getIssuers = <ThrowOnError extends boolean = false>(
  options?: Options<GetIssuersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetIssuersResponses,
    GetIssuersErrors,
    ThrowOnError
  >({ url: '/api/v1/issuers', ...options });

/**
 * Добавить
 */
export const postIssuers = <ThrowOnError extends boolean = false>(
  options: Options<PostIssuersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostIssuersResponses,
    PostIssuersErrors,
    ThrowOnError
  >({
    url: '/api/v1/issuers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отображает всю имеющуюся информацию по обменным курсам
 */
export const getForeignExchangeRates = <ThrowOnError extends boolean = false>(
  options?: Options<GetForeignExchangeRatesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetForeignExchangeRatesResponses,
    GetForeignExchangeRatesErrors,
    ThrowOnError
  >({ url: '/api/v1/foreign-exchange-rates', ...options });

/**
 * Добавить
 */
export const postForeignExchangeRates = <ThrowOnError extends boolean = false>(
  options: Options<PostForeignExchangeRatesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostForeignExchangeRatesResponses,
    PostForeignExchangeRatesErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить все
 *
 * Отображает все выплаты по всем счетам
 */
export const getEventCashFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetEventCashFlowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetEventCashFlowsResponses,
    GetEventCashFlowsErrors,
    ThrowOnError
  >({ url: '/api/v1/event-cash-flows', ...options });

/**
 * Добавить
 *
 * Сохранить информацию
 */
export const postEventCashFlows = <ThrowOnError extends boolean = false>(
  options: Options<PostEventCashFlowsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostEventCashFlowsResponses,
    PostEventCashFlowsErrors,
    ThrowOnError
  >({
    url: '/api/v1/event-cash-flows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отобразить по валюте
 *
 * Отображает всю имеющуюся информацию по обменному курсу заданной валютной пары
 */
export const getForeignExchangeRatesCurrencyPairsByCurrencyPair = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses,
    GetForeignExchangeRatesCurrencyPairsByCurrencyPairErrors,
    ThrowOnError
  >({
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}',
    ...options,
  });

/**
 * Отобразить все
 */
export const getCashFlowTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetCashFlowTypesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCashFlowTypesResponses,
    GetCashFlowTypesErrors,
    ThrowOnError
  >({ url: '/api/v1/cash-flow-types', ...options });

/**
 * Отобразить по идентификатору
 */
export const getCashFlowTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetCashFlowTypesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCashFlowTypesByIdResponses,
    GetCashFlowTypesByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/cash-flow-types/{id}', ...options });
