// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:2030' | (string & {});
};

export type Sdelka = {
  /**
   * Внутренний идентификатор сделки
   */
  id?: number;
  /**
   * Номер счета в системе учета брокера
   */
  portfolio: string;
  /**
   * Instrument
   */
  security: number;
  /**
   * Время сделки
   */
  timestamp: string;
  /**
   * Количество бумаг (контрактов), шт
   */
  count: number;
  /**
   * Номер сделки в системе учета брокера
   */
  'trade-id': string;
};

export type DvizhenieDsPoSdelke = {
  /**
   * Внутренний идентификатор записи
   */
  id?: number;
  /**
   * Сумма по событию
   */
  value: number;
  /**
   * Валюта
   */
  currency?: string;
  /**
   * Внутренний идентификатор сделки
   */
  'transaction-id': number;
  /**
   * Тип события (стоимость бумаг без НКД, НКД, комиссия)
   */
  'event-type':
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
};

export type Kotirovka = {
  /**
   * Внутренний идентификатор записи
   */
  id?: number;
  /**
   * Instrument
   */
  security: number;
  /**
   * Время
   */
  timestamp: string;
  /**
   * Kotirovka (для облигаций - в процентах, деривативы - в пунктах)
   */
  quote: number;
  /**
   * Kotirovka (в валюте, только для облигаций и деривативов)
   */
  price?: number;
  /**
   * НКД (в валюте, только для облигаций)
   */
  'accrued-interest'?: number;
  /**
   * Валюта котировки для акций, облигаций, произвольных активов и опционально для деривативов
   */
  currency?: string;
};

/**
 * Дивиденды, купоны, амортизация, вариационная маржа, налоги, комиссии
 */
export type SobytiePoBumage = {
  /**
   * Внутренний идентификатор записи
   */
  id?: number;
  /**
   * Номер счета в системе учета брокера
   */
  portfolio: string;
  /**
   * Время события
   */
  timestamp: string;
  /**
   * Instrument
   */
  security: number;
  /**
   * Количество бумаг (контрактов)
   */
  count: number;
  /**
   * Сумма
   */
  value: number;
  /**
   * Валюта
   */
  currency?: string;
  /**
   * Тип события
   */
  'event-type':
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
};

/**
 * Информация об инструменте
 */
export type SvojstvaInstrumenta = {
  /**
   * Внутренний идентификатор инструмента
   */
  security: number;
  /**
   * Сектор экономики (опционально)
   */
  sector?: string;
  /**
   * Внутренний идентификатор эмитента (опционально)
   */
  issuer?: number;
};

/**
 * Акция, облигация, валютная пара, фьючерс, опцион или произвольный актив
 */
export type Instrument = {
  /**
   * Внутренний идентификатор инструмента
   */
  id?: number;
  /**
   * Тип ценной бумаги
   */
  type:
    | 'STOCK'
    | 'BOND'
    | 'STOCK_OR_BOND'
    | 'DERIVATIVE'
    | 'CURRENCY_PAIR'
    | 'ASSET';
  /**
   * ISIN акций и облигаций (опционально)
   */
  isin?: string;
  /**
   * Тикер (опционально)
   */
  ticker?: string;
  /**
   * Наименование (опционально)
   */
  name?: string;
};

export type Schet = {
  /**
   * Номер счета в системе учета брокера
   */
  id: string;
  /**
   * Признак активного счета: если false то счет исключается из аналитического расчета
   */
  enabled: boolean;
};

export type SvojstvaScheta = {
  /**
   * Внутренний идентификатор записи
   */
  id?: number;
  /**
   * Номер счета
   */
  portfolio: string;
  /**
   * Информация актуальна на время
   */
  timestamp?: string;
  /**
   * Свойство портфеля
   */
  property: 'TOTAL_ASSETS_RUB' | 'TOTAL_ASSETS_USD';
  /**
   * Значение свойства
   */
  value: string;
};

export type OstatokDenezhnykhSredstv = {
  /**
   * Внутренний идентификатор
   */
  id?: number;
  /**
   * Номер счета в системе учета брокера
   */
  portfolio: string;
  /**
   * Значение актуально на дату
   */
  timestamp: string;
  /**
   * Рынок
   */
  market: string;
  /**
   * OstatokDenezhnykhSredstv
   */
  value: number;
  /**
   * Валюта
   */
  currency: string;
};

export type Emitent = {
  /**
   * Внутренний идентификатор эмитента
   */
  id?: number;
  /**
   * Идентификатор налогоплательщика (Россия - ИНН, США - EIN и т.д.)
   */
  taxpayerId?: string;
  /**
   * Наименование
   */
  name: string;
};

export type OfitsialnyjObmennyjKurs = {
  /**
   * Дата
   */
  date: string;
  /**
   * Значение обменного курса
   */
  rate: number;
  /**
   * Валютная пара, для курса доллара в рублях - USDRUB
   */
  'currency-pair': string;
};

/**
 * Ввод и вывод ДС, налоги, комиссии, а также выплаты по инструментам другого счета
 */
export type DvizhenieDsPoSchetu = {
  /**
   * Идентификатор записи
   */
  id?: number;
  /**
   * Номер счета
   */
  portfolio: string;
  /**
   * Время события
   */
  timestamp: string;
  /**
   * Значение
   */
  value: number;
  /**
   * Валюта
   */
  currency?: string;
  /**
   * Описание события
   */
  description?: string;
  /**
   * Тип события
   */
  'event-type':
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
};

export type PageableObject = {
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
};

export type PageSdelka = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<Sdelka>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type SortObject = {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
};

export type PageDvizhenieDsPoSdelke = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<DvizhenieDsPoSdelke>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageKotirovka = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<Kotirovka>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageSobytiePoBumage = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<SobytiePoBumage>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageSvojstvaInstrumenta = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<SvojstvaInstrumenta>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageInstrument = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<Instrument>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageSchet = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<Schet>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageSvojstvaScheta = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<SvojstvaScheta>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageOstatokDenezhnykhSredstv = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<OstatokDenezhnykhSredstv>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageEmitent = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<Emitent>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageOfitsialnyjObmennyjKurs = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<OfitsialnyjObmennyjKurs>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type PageDvizhenieDsPoSchetu = {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<DvizhenieDsPoSchetu>;
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
};

export type DeleteTransactionsByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор сделки
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/transactions/{id}';
};

export type DeleteTransactionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteTransactionsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteTransactionsByIdResponse =
  DeleteTransactionsByIdResponses[keyof DeleteTransactionsByIdResponses];

export type GetTransactionsByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор сделки
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/transactions/{id}';
};

export type GetTransactionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionsByIdResponses = {
  /**
   * OK
   */
  200: Sdelka;
};

export type GetTransactionsByIdResponse =
  GetTransactionsByIdResponses[keyof GetTransactionsByIdResponses];

export type PutTransactionsByIdData = {
  body: Sdelka;
  path: {
    /**
     * Внутренний идентификатор сделки
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/transactions/{id}';
};

export type PutTransactionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutTransactionsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutTransactionsByIdResponse =
  PutTransactionsByIdResponses[keyof PutTransactionsByIdResponses];

export type DeleteTransactionCashFlowsByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор сделки
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/transaction-cash-flows/{id}';
};

export type DeleteTransactionCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteTransactionCashFlowsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteTransactionCashFlowsByIdResponse =
  DeleteTransactionCashFlowsByIdResponses[keyof DeleteTransactionCashFlowsByIdResponses];

export type GetTransactionCashFlowsByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор сделки
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/transaction-cash-flows/{id}';
};

export type GetTransactionCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionCashFlowsByIdResponses = {
  /**
   * OK
   */
  200: DvizhenieDsPoSdelke;
};

export type GetTransactionCashFlowsByIdResponse =
  GetTransactionCashFlowsByIdResponses[keyof GetTransactionCashFlowsByIdResponses];

export type PutTransactionCashFlowsByIdData = {
  body: DvizhenieDsPoSdelke;
  path: {
    /**
     * Внутренний идентификатор сделки
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/transaction-cash-flows/{id}';
};

export type PutTransactionCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutTransactionCashFlowsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutTransactionCashFlowsByIdResponse =
  PutTransactionCashFlowsByIdResponses[keyof PutTransactionCashFlowsByIdResponses];

export type DeleteSecurityQuotesByIdData = {
  body?: never;
  path: {
    /**
     * Номер записи о котировке
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-quotes/{id}';
};

export type DeleteSecurityQuotesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecurityQuotesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecurityQuotesByIdResponse =
  DeleteSecurityQuotesByIdResponses[keyof DeleteSecurityQuotesByIdResponses];

export type GetSecurityQuotesByIdData = {
  body?: never;
  path: {
    /**
     * Номер записи о котировке
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-quotes/{id}';
};

export type GetSecurityQuotesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityQuotesByIdResponses = {
  /**
   * OK
   */
  200: Kotirovka;
};

export type GetSecurityQuotesByIdResponse =
  GetSecurityQuotesByIdResponses[keyof GetSecurityQuotesByIdResponses];

export type PutSecurityQuotesByIdData = {
  body: Kotirovka;
  path: {
    /**
     * Номер записи о котировке
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-quotes/{id}';
};

export type PutSecurityQuotesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecurityQuotesByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecurityQuotesByIdResponse =
  PutSecurityQuotesByIdResponses[keyof PutSecurityQuotesByIdResponses];

export type DeleteSecurityEventCashFlowsByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор выплаты
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-event-cash-flows/{id}';
};

export type DeleteSecurityEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecurityEventCashFlowsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecurityEventCashFlowsByIdResponse =
  DeleteSecurityEventCashFlowsByIdResponses[keyof DeleteSecurityEventCashFlowsByIdResponses];

export type GetSecurityEventCashFlowsByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор выплаты
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-event-cash-flows/{id}';
};

export type GetSecurityEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityEventCashFlowsByIdResponses = {
  /**
   * OK
   */
  200: SobytiePoBumage;
};

export type GetSecurityEventCashFlowsByIdResponse =
  GetSecurityEventCashFlowsByIdResponses[keyof GetSecurityEventCashFlowsByIdResponses];

export type PutSecurityEventCashFlowsByIdData = {
  body: SobytiePoBumage;
  path: {
    /**
     * Внутренний идентификатор выплаты
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-event-cash-flows/{id}';
};

export type PutSecurityEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecurityEventCashFlowsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecurityEventCashFlowsByIdResponse =
  PutSecurityEventCashFlowsByIdResponses[keyof PutSecurityEventCashFlowsByIdResponses];

export type DeleteSecurityDescriptionsByIdData = {
  body?: never;
  path: {
    /**
     * Идентификатор
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-descriptions/{id}';
};

export type DeleteSecurityDescriptionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecurityDescriptionsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecurityDescriptionsByIdResponse =
  DeleteSecurityDescriptionsByIdResponses[keyof DeleteSecurityDescriptionsByIdResponses];

export type GetSecurityDescriptionsByIdData = {
  body?: never;
  path: {
    /**
     * Идентификатор
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-descriptions/{id}';
};

export type GetSecurityDescriptionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityDescriptionsByIdResponses = {
  /**
   * OK
   */
  200: SvojstvaInstrumenta;
};

export type GetSecurityDescriptionsByIdResponse =
  GetSecurityDescriptionsByIdResponses[keyof GetSecurityDescriptionsByIdResponses];

export type PutSecurityDescriptionsByIdData = {
  body: SvojstvaInstrumenta;
  path: {
    /**
     * Идентификатор
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/security-descriptions/{id}';
};

export type PutSecurityDescriptionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecurityDescriptionsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecurityDescriptionsByIdResponse =
  PutSecurityDescriptionsByIdResponses[keyof PutSecurityDescriptionsByIdResponses];

export type DeleteSecuritiesByIdData = {
  body?: never;
  path: {
    /**
     * Идентификатор
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/securities/{id}';
};

export type DeleteSecuritiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteSecuritiesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteSecuritiesByIdResponse =
  DeleteSecuritiesByIdResponses[keyof DeleteSecuritiesByIdResponses];

export type GetSecuritiesByIdData = {
  body?: never;
  path: {
    /**
     * Идентификатор
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/securities/{id}';
};

export type GetSecuritiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecuritiesByIdResponses = {
  /**
   * OK
   */
  200: Instrument;
};

export type GetSecuritiesByIdResponse =
  GetSecuritiesByIdResponses[keyof GetSecuritiesByIdResponses];

export type PutSecuritiesByIdData = {
  body: Instrument;
  path: {
    /**
     * Идентификатор
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/securities/{id}';
};

export type PutSecuritiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutSecuritiesByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutSecuritiesByIdResponse =
  PutSecuritiesByIdResponses[keyof PutSecuritiesByIdResponses];

export type DeletePortfoliosByIdData = {
  body?: never;
  path: {
    /**
     * Номер счета
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/portfolios/{id}';
};

export type DeletePortfoliosByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeletePortfoliosByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePortfoliosByIdResponse =
  DeletePortfoliosByIdResponses[keyof DeletePortfoliosByIdResponses];

export type GetPortfoliosByIdData = {
  body?: never;
  path: {
    /**
     * Номер счета
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/portfolios/{id}';
};

export type GetPortfoliosByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfoliosByIdResponses = {
  /**
   * OK
   */
  200: Schet;
};

export type GetPortfoliosByIdResponse =
  GetPortfoliosByIdResponses[keyof GetPortfoliosByIdResponses];

export type PutPortfoliosByIdData = {
  body: Schet;
  path: {
    /**
     * Номер счета
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/portfolios/{id}';
};

export type PutPortfoliosByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutPortfoliosByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutPortfoliosByIdResponse =
  PutPortfoliosByIdResponses[keyof PutPortfoliosByIdResponses];

export type DeletePortfolioPropertiesByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор записи
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/portfolio-properties/{id}';
};

export type DeletePortfolioPropertiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeletePortfolioPropertiesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePortfolioPropertiesByIdResponse =
  DeletePortfolioPropertiesByIdResponses[keyof DeletePortfolioPropertiesByIdResponses];

export type GetPortfolioPropertiesByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор записи
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/portfolio-properties/{id}';
};

export type GetPortfolioPropertiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfolioPropertiesByIdResponses = {
  /**
   * OK
   */
  200: SvojstvaScheta;
};

export type GetPortfolioPropertiesByIdResponse =
  GetPortfolioPropertiesByIdResponses[keyof GetPortfolioPropertiesByIdResponses];

export type PutPortfolioPropertiesByIdData = {
  body: SvojstvaScheta;
  path: {
    /**
     * Внутренний идентификатор записи
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/portfolio-properties/{id}';
};

export type PutPortfolioPropertiesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutPortfolioPropertiesByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutPortfolioPropertiesByIdResponse =
  PutPortfolioPropertiesByIdResponses[keyof PutPortfolioPropertiesByIdResponses];

export type DeletePortfolioCashByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор записи
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/portfolio-cash/{id}';
};

export type DeletePortfolioCashByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeletePortfolioCashByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePortfolioCashByIdResponse =
  DeletePortfolioCashByIdResponses[keyof DeletePortfolioCashByIdResponses];

export type GetPortfolioCashByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор записи
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/portfolio-cash/{id}';
};

export type GetPortfolioCashByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfolioCashByIdResponses = {
  /**
   * OK
   */
  200: OstatokDenezhnykhSredstv;
};

export type GetPortfolioCashByIdResponse =
  GetPortfolioCashByIdResponses[keyof GetPortfolioCashByIdResponses];

export type PutPortfolioCashByIdData = {
  body: OstatokDenezhnykhSredstv;
  path: {
    /**
     * Внутренний идентификатор записи
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/portfolio-cash/{id}';
};

export type PutPortfolioCashByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutPortfolioCashByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutPortfolioCashByIdResponse =
  PutPortfolioCashByIdResponses[keyof PutPortfolioCashByIdResponses];

export type DeleteIssuersByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор эмитента
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/issuers/{id}';
};

export type DeleteIssuersByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteIssuersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteIssuersByIdResponse =
  DeleteIssuersByIdResponses[keyof DeleteIssuersByIdResponses];

export type GetIssuersByIdData = {
  body?: never;
  path: {
    /**
     * Внутренний идентификатор эмитента
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/issuers/{id}';
};

export type GetIssuersByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetIssuersByIdResponses = {
  /**
   * OK
   */
  200: Emitent;
};

export type GetIssuersByIdResponse =
  GetIssuersByIdResponses[keyof GetIssuersByIdResponses];

export type PutIssuersByIdData = {
  body: Emitent;
  path: {
    /**
     * Внутренний идентификатор эмитента
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/issuers/{id}';
};

export type PutIssuersByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutIssuersByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutIssuersByIdResponse =
  PutIssuersByIdResponses[keyof PutIssuersByIdResponses];

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData =
  {
    body?: never;
    path: {
      /**
       * Валютная пара
       */
      'currency-pair': string;
      /**
       * Дата
       */
      date: string;
    };
    query?: never;
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}/dates/{date}';
  };

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors =
  {
    /**
     * Internal Server Error
     */
    500: unknown;
  };

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses =
  {
    /**
     * No Content
     */
    204: void;
  };

export type DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponse =
  DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses[keyof DeleteForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses];

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData =
  {
    body?: never;
    path: {
      /**
       * Валютная пара
       */
      'currency-pair': string;
      /**
       * Дата
       */
      date: string;
    };
    query?: never;
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}/dates/{date}';
  };

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors =
  {
    /**
     * Internal Server Error
     */
    500: unknown;
  };

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses =
  {
    /**
     * OK
     */
    200: OfitsialnyjObmennyjKurs;
  };

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponse =
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses[keyof GetForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses];

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateData =
  {
    body: OfitsialnyjObmennyjKurs;
    path: {
      /**
       * Валютная пара
       */
      'currency-pair': string;
      /**
       * Дата
       */
      date: string;
    };
    query?: never;
    url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}/dates/{date}';
  };

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateErrors =
  {
    /**
     * Internal Server Error
     */
    500: unknown;
  };

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses =
  {
    /**
     * Created
     */
    201: unknown;
    /**
     * No Content
     */
    204: void;
  };

export type PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponse =
  PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses[keyof PutForeignExchangeRatesCurrencyPairsByCurrencyPairDatesByDateResponses];

export type DeleteEventCashFlowsByIdData = {
  body?: never;
  path: {
    /**
     * Номер события
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/event-cash-flows/{id}';
};

export type DeleteEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteEventCashFlowsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteEventCashFlowsByIdResponse =
  DeleteEventCashFlowsByIdResponses[keyof DeleteEventCashFlowsByIdResponses];

export type GetEventCashFlowsByIdData = {
  body?: never;
  path: {
    /**
     * Номер события
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/event-cash-flows/{id}';
};

export type GetEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetEventCashFlowsByIdResponses = {
  /**
   * OK
   */
  200: DvizhenieDsPoSchetu;
};

export type GetEventCashFlowsByIdResponse =
  GetEventCashFlowsByIdResponses[keyof GetEventCashFlowsByIdResponses];

export type PutEventCashFlowsByIdData = {
  body: DvizhenieDsPoSchetu;
  path: {
    /**
     * Номер события
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/event-cash-flows/{id}';
};

export type PutEventCashFlowsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutEventCashFlowsByIdResponses = {
  /**
   * Created
   */
  201: unknown;
  /**
   * No Content
   */
  204: void;
};

export type PutEventCashFlowsByIdResponse =
  PutEventCashFlowsByIdResponses[keyof PutEventCashFlowsByIdResponses];

export type GetTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Идентификатор счета брокера
     */
    portfolio?: string;
    /**
     * Номер сделки в системе учета брокера
     */
    'trade-id'?: string;
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/transactions';
};

export type GetTransactionsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionsResponses = {
  /**
   * OK
   */
  200: PageSdelka;
};

export type GetTransactionsResponse =
  GetTransactionsResponses[keyof GetTransactionsResponses];

export type PostTransactionsData = {
  body: Sdelka;
  path?: never;
  query?: never;
  url: '/api/v1/transactions';
};

export type PostTransactionsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostTransactionsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetTransactionCashFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Номер счета
     */
    portfolio?: string;
    /**
     * Номер сделки в системе учета брокера
     */
    'trade-id'?: string;
    /**
     * Тип (стоимость/комиссия/НКД)
     */
    'event-type'?: number;
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/transaction-cash-flows';
};

export type GetTransactionCashFlowsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetTransactionCashFlowsResponses = {
  /**
   * OK
   */
  200: PageDvizhenieDsPoSdelke;
};

export type GetTransactionCashFlowsResponse =
  GetTransactionCashFlowsResponses[keyof GetTransactionCashFlowsResponses];

export type PostTransactionCashFlowsData = {
  body: DvizhenieDsPoSdelke;
  path?: never;
  query?: never;
  url: '/api/v1/transaction-cash-flows';
};

export type PostTransactionCashFlowsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostTransactionCashFlowsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetSecurityQuotesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/security-quotes';
};

export type GetSecurityQuotesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityQuotesResponses = {
  /**
   * OK
   */
  200: PageKotirovka;
};

export type GetSecurityQuotesResponse =
  GetSecurityQuotesResponses[keyof GetSecurityQuotesResponses];

export type PostSecurityQuotesData = {
  body: Kotirovka;
  path?: never;
  query?: never;
  url: '/api/v1/security-quotes';
};

export type PostSecurityQuotesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecurityQuotesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetSecurityEventCashFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/security-event-cash-flows';
};

export type GetSecurityEventCashFlowsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityEventCashFlowsResponses = {
  /**
   * OK
   */
  200: PageSobytiePoBumage;
};

export type GetSecurityEventCashFlowsResponse =
  GetSecurityEventCashFlowsResponses[keyof GetSecurityEventCashFlowsResponses];

export type PostSecurityEventCashFlowsData = {
  body: SobytiePoBumage;
  path?: never;
  query?: never;
  url: '/api/v1/security-event-cash-flows';
};

export type PostSecurityEventCashFlowsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecurityEventCashFlowsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetSecurityDescriptionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/security-descriptions';
};

export type GetSecurityDescriptionsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecurityDescriptionsResponses = {
  /**
   * OK
   */
  200: PageSvojstvaInstrumenta;
};

export type GetSecurityDescriptionsResponse =
  GetSecurityDescriptionsResponses[keyof GetSecurityDescriptionsResponses];

export type PostSecurityDescriptionsData = {
  body: SvojstvaInstrumenta;
  path?: never;
  query?: never;
  url: '/api/v1/security-descriptions';
};

export type PostSecurityDescriptionsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecurityDescriptionsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetSecuritiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/securities';
};

export type GetSecuritiesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetSecuritiesResponses = {
  /**
   * OK
   */
  200: PageInstrument;
};

export type GetSecuritiesResponse =
  GetSecuritiesResponses[keyof GetSecuritiesResponses];

export type PostSecuritiesData = {
  body: Instrument;
  path?: never;
  query?: never;
  url: '/api/v1/securities';
};

export type PostSecuritiesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostSecuritiesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetPortfoliosData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/portfolios';
};

export type GetPortfoliosErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfoliosResponses = {
  /**
   * OK
   */
  200: PageSchet;
};

export type GetPortfoliosResponse =
  GetPortfoliosResponses[keyof GetPortfoliosResponses];

export type PostPortfoliosData = {
  body: Schet;
  path?: never;
  query?: never;
  url: '/api/v1/portfolios';
};

export type PostPortfoliosErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostPortfoliosResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetPortfolioPropertiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/portfolio-properties';
};

export type GetPortfolioPropertiesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfolioPropertiesResponses = {
  /**
   * OK
   */
  200: PageSvojstvaScheta;
};

export type GetPortfolioPropertiesResponse =
  GetPortfolioPropertiesResponses[keyof GetPortfolioPropertiesResponses];

export type PostPortfolioPropertiesData = {
  body: SvojstvaScheta;
  path?: never;
  query?: never;
  url: '/api/v1/portfolio-properties';
};

export type PostPortfolioPropertiesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostPortfolioPropertiesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetPortfolioCashData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/portfolio-cash';
};

export type GetPortfolioCashErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPortfolioCashResponses = {
  /**
   * OK
   */
  200: PageOstatokDenezhnykhSredstv;
};

export type GetPortfolioCashResponse =
  GetPortfolioCashResponses[keyof GetPortfolioCashResponses];

export type PostPortfolioCashData = {
  body: OstatokDenezhnykhSredstv;
  path?: never;
  query?: never;
  url: '/api/v1/portfolio-cash';
};

export type PostPortfolioCashErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostPortfolioCashResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetIssuersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/issuers';
};

export type GetIssuersErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetIssuersResponses = {
  /**
   * OK
   */
  200: PageEmitent;
};

export type GetIssuersResponse = GetIssuersResponses[keyof GetIssuersResponses];

export type PostIssuersData = {
  body: Emitent;
  path?: never;
  query?: never;
  url: '/api/v1/issuers';
};

export type PostIssuersErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostIssuersResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetForeignExchangeRatesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/foreign-exchange-rates';
};

export type GetForeignExchangeRatesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetForeignExchangeRatesResponses = {
  /**
   * OK
   */
  200: PageOfitsialnyjObmennyjKurs;
};

export type GetForeignExchangeRatesResponse =
  GetForeignExchangeRatesResponses[keyof GetForeignExchangeRatesResponses];

export type PostForeignExchangeRatesData = {
  body: OfitsialnyjObmennyjKurs;
  path?: never;
  query?: never;
  url: '/api/v1/foreign-exchange-rates';
};

export type PostForeignExchangeRatesErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostForeignExchangeRatesResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetEventCashFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: '/api/v1/event-cash-flows';
};

export type GetEventCashFlowsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetEventCashFlowsResponses = {
  /**
   * OK
   */
  200: PageDvizhenieDsPoSchetu;
};

export type GetEventCashFlowsResponse =
  GetEventCashFlowsResponses[keyof GetEventCashFlowsResponses];

export type PostEventCashFlowsData = {
  body: DvizhenieDsPoSchetu;
  path?: never;
  query?: never;
  url: '/api/v1/event-cash-flows';
};

export type PostEventCashFlowsErrors = {
  /**
   * Conflict
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostEventCashFlowsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairData = {
  body?: never;
  path: {
    /**
     * Валютная пара
     */
    'currency-pair': string;
  };
  query?: never;
  url: '/api/v1/foreign-exchange-rates/currency-pairs/{currency-pair}';
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses = {
  /**
   * OK
   */
  200: Array<OfitsialnyjObmennyjKurs>;
};

export type GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponse =
  GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses[keyof GetForeignExchangeRatesCurrencyPairsByCurrencyPairResponses];

export type GetCashFlowTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/cash-flow-types';
};

export type GetCashFlowTypesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetCashFlowTypesResponses = {
  /**
   * OK
   */
  200: Array<
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE'
  >;
};

export type GetCashFlowTypesResponse =
  GetCashFlowTypesResponses[keyof GetCashFlowTypesResponses];

export type GetCashFlowTypesByIdData = {
  body?: never;
  path: {
    /**
     * Идентификатор типа
     */
    id: number;
  };
  query?: never;
  url: '/api/v1/cash-flow-types/{id}';
};

export type GetCashFlowTypesByIdErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetCashFlowTypesByIdResponses = {
  /**
   * OK
   */
  200:
    | 'CASH'
    | 'PRICE'
    | 'ACCRUED_INTEREST'
    | 'FEE'
    | 'AMORTIZATION'
    | 'REDEMPTION'
    | 'COUPON'
    | 'DIVIDEND'
    | 'DERIVATIVE_PROFIT'
    | 'MARGIN'
    | 'TAX'
    | 'FORECAST_TAX'
    | 'DERIVATIVE_PRICE'
    | 'DERIVATIVE_QUOTE';
};

export type GetCashFlowTypesByIdResponse =
  GetCashFlowTypesByIdResponses[keyof GetCashFlowTypesByIdResponses];
